# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PINCTRL_HAILO15)	+= pinctrl-hailo15.o
obj-$(CONFIG_PINCTRL_HAILO15)	+= pinctrl-hailo15-cpld.o
obj-$(CONFIG_PINCTRL_HAILO15)	+= hailo15_cpld_of_evb_rev1.dtb.o
obj-$(CONFIG_PINCTRL_HAILO15)	+= hailo15_cpld_of_evb_rev2.dtb.o