/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019-2023 Hailo Technologies Ltd. All rights reserved.
 */

#ifndef HAILO15_SCMI_API_H
#define HAILO15_SCMI_API_H

#define SCU_FW_MAJOR 0
#define SCU_FW_MINOR 31
#define SCU_FW_REVISION 2
#define SCU_FW_BUILD_VERSION (((SCU_FW_MAJOR) << 24) | ((SCU_FW_MINOR) << 16) | (SCU_FW_REVISION))

#define HAILO15_SCMI_SENSOR_IDX_PVT_TEMPERATURE_SENSOR_0 0
#define HAILO15_SCMI_SENSOR_IDX_PVT_TEMPERATURE_SENSOR_1 1

/* Clocks IDs */
#define HAILO15_SCMI_CLOCK_IDX_HCLK 0
#define HAILO15_SCMI_CLOCK_IDX_SDIO_0_M_HCLK 1
#define HAILO15_SCMI_CLOCK_IDX_SDIO_1_M_HCLK 2
#define HAILO15_SCMI_CLOCK_IDX_DSP_CONFIG 3
#define HAILO15_SCMI_CLOCK_IDX_DSP_PLL 4
#define HAILO15_SCMI_CLOCK_IDX_DSP 5
#define HAILO15_SCMI_CLOCK_IDX_ETHERNET_PCLK 6
#define HAILO15_SCMI_CLOCK_IDX_ETHERNET_ACLK 7
#define HAILO15_SCMI_CLOCK_IDX_SDIO_0_CARD_CLK 8
#define HAILO15_SCMI_CLOCK_IDX_SDIO_1_CARD_CLK 9
#define HAILO15_SCMI_CLOCK_IDX_VISION_HCLK 10
#define HAILO15_SCMI_CLOCK_IDX_ISP_WRAPPER_PCLK 11
#define HAILO15_SCMI_CLOCK_IDX_CSI_RX0_PCLK 12
#define HAILO15_SCMI_CLOCK_IDX_CSI_RX1_PCLK 13
#define HAILO15_SCMI_CLOCK_IDX_CSI_TX0_PCLK 14
#define HAILO15_SCMI_CLOCK_IDX_VISION_CLK 15
#define HAILO15_SCMI_CLOCK_IDX_ISP_WRAPPER_CLK 16
#define HAILO15_SCMI_CLOCK_IDX_CSI_RX0_CLK 17
#define HAILO15_SCMI_CLOCK_IDX_CSI_RX1_CLK 18
#define HAILO15_SCMI_CLOCK_IDX_CSI_TX0_CLK 19
#define HAILO15_SCMI_CLOCK_IDX_CSI_RX0_XTAL_CLK 20
#define HAILO15_SCMI_CLOCK_IDX_CSI_RX1_XTAL_CLK 21
#define HAILO15_SCMI_CLOCK_IDX_CSI_TX0_XTAL_CLK 22
#define HAILO15_SCMI_CLOCK_IDX_MIPI_REF_CLK 23
#define HAILO15_SCMI_CLOCK_IDX_MIPI_ESC_CLK 24
#define HAILO15_SCMI_CLOCK_IDX_SDIO_0_CLK_DIV_BYPASS 25
#define HAILO15_SCMI_CLOCK_IDX_SDIO_1_CLK_DIV_BYPASS 26
#define HAILO15_SCMI_CLOCK_IDX_I2S_CLK_DIV 27

/* Resets IDs */
#define HAILO15_SCMI_RESET_IDX_CORE_CPU 0
#define HAILO15_SCMI_RESET_IDX_NN_CORE 1
#define HAILO15_SCMI_RESET_IDX_SDIO1_8BIT_MUX 2
#define HAILO15_SCMI_RESET_IDX_SYSTEM_RESET 3
#define HAILO15_SCMI_RESET_IDX_DSP 4
#define HAILO15_SCMI_RESET_IDX_SDIO_0_CD_FROM_PINMUX 5
#define HAILO15_SCMI_RESET_IDX_SDIO_1_CD_FROM_PINMUX 6

/* Hailo IDs */
#define HAILO15_SCMI_HAILO_GET_SCU_BOOT_SOURCE_ID 3
#define HAILO15_SCMI_HAILO_CONFIGURE_ETH_DELAY_ID 4
#define HAILO15_SCMI_HAILO_GET_FUSE_INFO_ID 5
#define HAILO15_SCMI_HAILO_SET_ETH_RMII_MODE 6

#endif /* HAILO15_SCMI_API_H */
