/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019-2023 Hailo Technologies Ltd. All rights reserved.
 *
 */

#ifndef _DT_BINDINGS_HAILO15_INTERRUPTS
#define _DT_BINDINGS_HAILO15_INTERRUPTS


#define  HW_INTERRUPTS__AP_ERROR_INTR_IRQ                                                	(122)
#define  HW_INTERRUPTS__AP_FUNC_INTR_IRQ                                                 	(123)
#define  HW_INTERRUPTS__ARM_MAILBOX_A53_INTR_0_IRQ                                       	(103)
#define  HW_INTERRUPTS__ARM_MAILBOX_A53_INTR_1_IRQ                                       	(104)
#define  HW_INTERRUPTS__ARM_MAILBOX_A53_INTR_2_IRQ                                       	(105)
#define  HW_INTERRUPTS__ARM_MAILBOX_A53_INTR_3_IRQ                                       	(116)
#define  HW_INTERRUPTS__ARM_MAILBOX_M4_INTR_0_IRQ                                        	( 57)
#define  HW_INTERRUPTS__ARM_MAILBOX_M4_INTR_1_IRQ                                        	( 58)
#define  HW_INTERRUPTS__CC_HOST_IRQ                                                      	(117)
#define  HW_INTERRUPTS__CPU0_FLOATING_POINT_IRQ                                          	( 63)
#define  HW_INTERRUPTS__CPU0_MAILBOX_IRQ                                                 	( 61)
#define  HW_INTERRUPTS__CPU0_SEMAPHORE_IRQ                                               	( 59)
#define  HW_INTERRUPTS__CPU1_FLOATING_POINT_IRQ                                          	( 64)
#define  HW_INTERRUPTS__CPU1_MAILBOX_IRQ                                                 	( 62)
#define  HW_INTERRUPTS__CPU1_SEMAPHORE_IRQ                                               	( 60)
#define  HW_INTERRUPTS__CPU_SUBSYS_ERROR_INT_IRQ                                         	(120)
#define  HW_INTERRUPTS__CSI_RX0_IRQ                                                      	( 36)
#define  HW_INTERRUPTS__CSI_RX1_IRQ                                                      	( 37)
#define  HW_INTERRUPTS__CSI_TX0_IRQ                                                      	( 40)
#define  HW_INTERRUPTS__CSI_TX0_DSI_IRQ                                                  	( 73)
#define  HW_INTERRUPTS__CSI_TX0_WRAPPER_FUNCTIONAL_INT_IRQ                               	( 39)
#define  HW_INTERRUPTS__DDR_CONTROLLER_INT_IRQ                                           	( 42)
#define  HW_INTERRUPTS__DDR_SUBSYS_ERR_INT_IRQ                                           	( 92)
#define  HW_INTERRUPTS__DDR_SUBSYS_FUNC_INT_IRQ                                          	( 95)
#define  HW_INTERRUPTS__DEBUG_TOP_ERROR_STATUS_OUT_IRQ                                   	( 69)
#define  HW_INTERRUPTS__DEBUG_TRIGGER_IRQ                                                	( 34)
#define  HW_INTERRUPTS__DMA0_IRQ                                                         	( 35)
#define  HW_INTERRUPTS__DRAM_DMA_AP0_INT_IRQ                                             	( 50)
#define  HW_INTERRUPTS__DRAM_DMA_AP1_INT_IRQ                                             	( 51)
#define  HW_INTERRUPTS__DRAM_DMA_AP2_INT_IRQ                                             	( 52)
#define  HW_INTERRUPTS__DRAM_DMA_CS0_IRQ_FUNC_IRQ                                        	( 44)
#define  HW_INTERRUPTS__DRAM_DMA_CS1_IRQ_FUNC_IRQ                                        	( 45)
#define  HW_INTERRUPTS__DRAM_DMA_CS2_IRQ_FUNC_IRQ                                        	( 46)
#define  HW_INTERRUPTS__DRAM_DMA_ENGINE0_IRQ_ERR_IRQ                                     	( 47)
#define  HW_INTERRUPTS__DRAM_DMA_ENGINE1_IRQ_ERR_IRQ                                     	( 48)
#define  HW_INTERRUPTS__DRAM_DMA_ENGINE2_IRQ_ERR_IRQ                                     	( 49)
#define  HW_INTERRUPTS__DRAM_DMA_WRAPPER_ERR_INT_IRQ                                     	(121)
#define  HW_INTERRUPTS__DSP_ERR_IRQ_IRQ                                                  	( 72)
#define  HW_INTERRUPTS__DSP_PWAITMODE_INTERRUPT_IRQ                                      	( 71)
#define  HW_INTERRUPTS__DSP_VIRT_CH_DONE_INTERRUPT_IRQ                                   	( 70)
#define  HW_INTERRUPTS__ETHERNET_0_IRQ                                                   	( 75)
#define  HW_INTERRUPTS__ETHERNET_1_IRQ                                                   	( 76)
#define  HW_INTERRUPTS__ETHERNET_10_IRQ                                                  	( 85)
#define  HW_INTERRUPTS__ETHERNET_11_IRQ                                                  	( 86)
#define  HW_INTERRUPTS__ETHERNET_12_IRQ                                                  	( 87)
#define  HW_INTERRUPTS__ETHERNET_13_IRQ                                                  	( 88)
#define  HW_INTERRUPTS__ETHERNET_14_IRQ                                                  	( 89)
#define  HW_INTERRUPTS__ETHERNET_15_IRQ                                                  	( 90)
#define  HW_INTERRUPTS__ETHERNET_2_IRQ                                                   	( 77)
#define  HW_INTERRUPTS__ETHERNET_3_IRQ                                                   	( 78)
#define  HW_INTERRUPTS__ETHERNET_4_IRQ                                                   	( 79)
#define  HW_INTERRUPTS__ETHERNET_5_IRQ                                                   	( 80)
#define  HW_INTERRUPTS__ETHERNET_6_IRQ                                                   	( 81)
#define  HW_INTERRUPTS__ETHERNET_7_IRQ                                                   	( 82)
#define  HW_INTERRUPTS__ETHERNET_8_IRQ                                                   	( 83)
#define  HW_INTERRUPTS__ETHERNET_9_IRQ                                                   	( 84)
#define  HW_INTERRUPTS__ETHERNET_ERR_INT_IRQ                                             	( 91)
#define  HW_INTERRUPTS__FASTBUS_INTR_STATUS_OUT_IRQ                                      	(106)
#define  HW_INTERRUPTS__FLASH_CACHE_IRQ                                                  	(119)
#define  HW_INTERRUPTS__GPIO_IRQ                                                         	( 43)
#define  HW_INTERRUPTS__H265_INT_IRQ                                                     	(109)
#define  HW_INTERRUPTS__I2C0_IRQ                                                         	(  9)
#define  HW_INTERRUPTS__I2C1_IRQ                                                         	( 10)
#define  HW_INTERRUPTS__I2C2_IRQ                                                         	( 11)
#define  HW_INTERRUPTS__I2C3_IRQ                                                         	( 12)
#define  HW_INTERRUPTS__I2S_IRQ                                                          	( 15)
#define  HW_INTERRUPTS__ISP_FUNC_INTERRUPT_IRQ                                           	(118)
#define  HW_INTERRUPTS__NN_CORE_CLUSTER_BREAKPOINT_IRQ                                   	( 93)
#define  HW_INTERRUPTS__NN_CORE_CONTEXT_SW_INTR_IRQ                                      	( 94)
#define  HW_INTERRUPTS__NN_CORE_ERROR_IRQ                                                	( 97)
#define  HW_INTERRUPTS__NN_CORE_INBOUND_DATA_IRQ                                         	( 98)
#define  HW_INTERRUPTS__NN_CORE_INFO_IRQ                                                 	( 96)
#define  HW_INTERRUPTS__NN_CORE_OUTBOUND_DATA_INTR_IRQ                                   	(102)
#define  HW_INTERRUPTS__PCIE_ERROR_IRQ                                                   	( 99)
#define  HW_INTERRUPTS__PCIE_FUNC_IRQ                                                    	(127)
#define  HW_INTERRUPTS__PVT_IRQ                                                          	(126)
#define  HW_INTERRUPTS__QSPI_FLASH_IRQ                                                   	( 33)
#define  HW_INTERRUPTS__SAFETY_AGGREGATOR_FATAL_INTR_IRQ                                 	(100)
#define  HW_INTERRUPTS__SAFETY_AGGREGATOR_NONFATAL_INTR_IRQ                              	(101)
#define  HW_INTERRUPTS__SDIO0_IRQ                                                        	(115)
#define  HW_INTERRUPTS__SDIO0_GP_IN_IRQ                                                  	( 67)
#define  HW_INTERRUPTS__SDIO0_LED_CONTROL_IRQ                                            	(114)
#define  HW_INTERRUPTS__SDIO0_WAKEUP_IRQ                                                 	(113)
#define  HW_INTERRUPTS__SDIO1_IRQ                                                        	(112)
#define  HW_INTERRUPTS__SDIO1_GP_IN_IRQ                                                  	( 68)
#define  HW_INTERRUPTS__SDIO1_LED_CONTROL_IRQ                                            	(111)
#define  HW_INTERRUPTS__SDIO1_WAKEUP_IRQ                                                 	(110)
#define  HW_INTERRUPTS__SW_DMA_AP_INT_0_IRQ                                              	( 53)
#define  HW_INTERRUPTS__SW_DMA_AP_INT_1_IRQ                                              	( 54)
#define  HW_INTERRUPTS__SW_DMA_AP_INT_2_IRQ                                              	(124)
#define  HW_INTERRUPTS__SW_DMA_AP_INT_3_IRQ                                              	(125)
#define  HW_INTERRUPTS__SW_DMA_ERR_INT_IRQ                                               	( 74)
#define  HW_INTERRUPTS__TIMEOUT_MONITOR_TIMEOUT_REACHED_FAST_BUS_IRQ                     	( 66)
#define  HW_INTERRUPTS__TIMEOUT_MONITOR_TIMEOUT_REACHED_TOP_AHB_BUS_IRQ                  	( 65)
#define  HW_INTERRUPTS__TIMER0_IRQ                                                       	( 28)
#define  HW_INTERRUPTS__TIMER1_IRQ                                                       	( 29)
#define  HW_INTERRUPTS__TIMER2_IRQ                                                       	( 30)
#define  HW_INTERRUPTS__TIMER3_IRQ                                                       	( 31)
#define  HW_INTERRUPTS__UART0_IRQ_IRQ                                                    	(  1)
#define  HW_INTERRUPTS__UART1_IRQ_IRQ                                                    	(  2)
#define  HW_INTERRUPTS__UART2_IRQ_IRQ                                                    	(  3)
#define  HW_INTERRUPTS__UART3_IRQ_IRQ                                                    	(  4)
#define  HW_INTERRUPTS__USB_ERROR_INTR_IRQ                                               	( 56)
#define  HW_INTERRUPTS__USB_INFO_INTR_IRQ                                                	( 55)
#define  HW_INTERRUPTS__VISION_BUFFER_READY_AP_INT_IRQ                                   	( 41)
#define  HW_INTERRUPTS__VISION_SUBSYS_ERR_INT_IRQ                                        	( 38)
#define  HW_INTERRUPTS__WATCHDOG0_IRQ                                                    	(107)
#define  HW_INTERRUPTS__WATCHDOG1_IRQ                                                    	(108)

#endif /* _DT_BINDINGS_HAILO15_INTERRUPTS */
