/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019-2024 Hailo Technologies Ltd. All rights reserved.
 */

#ifndef HAILO15_RELEASE_VERSION_H
#define HAILO15_RELEASE_VERSION_H

#define HAILO_LINUX_RELEASE_MAJOR 1
#define HAILO_LINUX_RELEASE_MINOR 7
#define HAILO_LINUX_RELEASE_REVISION 3
#define HAILO_LINUX_RELEASE_BUILD_VERSION (((HAILO_LINUX_RELEASE_MAJOR) << 24) | ((HAILO_LINUX_RELEASE_MINOR) << 16) | (HAILO_LINUX_RELEASE_REVISION))

#endif /* HAILO15_RELEASE_VERSION_H */
